name: Sphinx build

on: 
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: python -m pip install sphinx sphinx-rtd-theme sphinx-gallery pytest

      - run: python -m pip install -e . 

      - name: Build HTML
        run: |
          cd docs
          make html
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: html-docs
          path: docs/_build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
